// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//  import 'firebase_options.dart';
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  ) {
//    // TODO: implement initializeApp
//    throw UnimplementedError();
//  }

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch(defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.fuchsia:
        return web;
      case TargetPlatform.linux:
        return web;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );

    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1WObCQytNvy4gM4njCRgbz6Emehdw8qE',
    appId: '1:915709747150:android:2b4e671164a94f5e21559f',
    messagingSenderId: '915709747150',
    projectId: 'flutter-stor-6b633',
    authDomain: 'chat-app-d17c9.firebaseapp.com',
    storageBucket: 'flutter-stor-6b633.appspot.com',
    measurementId: 'G-KGMX1F5LCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbbSyq-TzXRqTPR6SSS2WtVx7efRgZJ0E',
    appId: '1:199298705970:android:b99068f00f91abffdaaa2b',
    messagingSenderId: '199298705970',
    projectId: 'chat-87f93',
    storageBucket: 'chat-87f93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtGwtG5z7cB9zpUDjzlSlvD1ntux7qapY',
    appId: '1:1046617815837:ios:5a5b845909559100043ff4',
    messagingSenderId: '1046617815837',
    projectId: 'chat-app-d17c9',
    storageBucket: 'chat-app-d17c9.appspot.com',
    iosClientId: '1046617815837-91p6unqg2cuekro6j52irscb78usjs5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
